import { Timestamp } from 'firebase/firestore';

// ----------------------------------------------------------------------------
// 1. Branches Collection
// Path: /branches/{branchId}
// ----------------------------------------------------------------------------
export interface Branch {
    name: string;
    location: string;
    managerId: string;
    placeId: string;               // NEW: Google Places ID
    status: 'active' | 'inactive';
    totalReviews: number;          // Default: 0
    averageRating: number;         // Default: 0
    positiveReviews: number;       // Default: 0
    negativeReviews: number;       // Default: 0
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 2. Staff Collection
// Path: /staff/{staffId}
// ----------------------------------------------------------------------------
export interface Staff {
    name: string;
    branchId: string;              // Refers to a Branch document ID
    role: string;                  // e.g., 'Manager', 'Waiter', 'Chef'
    email?: string;                // Optional
    performanceScore: number;      // Default: 0
    totalReviewsTagged: number;    // Default: 0
    averageRating: number;         // Default: 0
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 3. Reviews Collection
// Path: /reviews/{reviewId}
// ----------------------------------------------------------------------------
export interface Review {
    branchId: string;              // Refers to a Branch document ID
    source: 'internal' | 'google' | 'zomato';
    externalReviewId?: string;     // NEW: Unique ID for duplicate prevention
    authorName: string;            // NEW: Review author
    rating: number;                // 1-5 scale
    reviewText: string;
    sentiment: 'pending' | 'positive' | 'neutral' | 'negative';
    sentimentScore: number;        // 0-1 AI score
    category: 'pending' | 'Food' | 'Service' | 'Staff' | 'Ambience' | 'Cleanliness';
    tags?: string[];               // Optional keywords
    staffTagged?: string;          // Refers to a Staff document ID (Optional)
    status: 'normal' | 'critical' | 'escalated'; // If rating <= 2 or sentiment == negative -> 'critical'
    responseStatus: 'pending' | 'responded'; // Defaults to 'pending'
    externalTimestamp?: number;    // NEW: Google review time
    syncedAt?: Timestamp;          // NEW: Google sync time
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 4. Responses Collection
// Path: /responses/{responseId}
// ----------------------------------------------------------------------------
export interface Response {
    reviewId: string;              // Refers to a Review document ID
    responseText: string;
    autoGenerated: boolean;
    respondedBy: string;           // Refers to a User document ID
    respondedAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 5. Users Collection
// Path: /users/{userId} 
// Document ID MUST match Firebase Authentication UID
// ----------------------------------------------------------------------------
export interface User {
    name: string;
    email: string;                 // NEW
    role: 'admin' | 'branch_manager' | 'staff';
    branchId?: string;             // Refers to a Branch document ID (Null for admins)
    isActive: boolean;             // NEW
    createdAt: Timestamp;
}
