import { Timestamp } from 'firebase/firestore';

// ----------------------------------------------------------------------------
// 1. Branches Collection
// Path: /branches/{branchId}
// ----------------------------------------------------------------------------
export interface Branch {
    name: string;
    location: string;
    managerId: string;
    placeId: string;               // NEW: Google Places ID
    status: 'active' | 'inactive';
    totalReviews: number;          // Default: 0
    averageRating: number;         // Default: 0
    positiveReviews: number;       // Default: 0
    negativeReviews: number;       // Default: 0
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 2. Staff Collection
// Path: /staff/{staffId}
// ----------------------------------------------------------------------------
export interface Staff {
    name: string;
    branchId: string;              // Refers to a Branch document ID
    role: string;                  // e.g., 'Manager', 'Waiter', 'Chef'
    email?: string;                // Optional
    performanceScore: number;      // Default: 0
    totalReviewsTagged: number;    // Default: 0
    averageRating: number;         // Default: 0
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 3. Reviews Collection
// Path: /reviews/{reviewId}
// ----------------------------------------------------------------------------
export interface Review {
    branchId: string;              // Refers to a Branch document ID
    source: 'internal' | 'google' | 'zomato';
    externalReviewId?: string;     // NEW: Unique ID for duplicate prevention
    authorName: string;            // NEW: Review author
    rating: number;                // 1-5 scale
    reviewText: string;
    sentiment: 'pending' | 'positive' | 'neutral' | 'negative';
    sentimentScore: number;        // 0-1 AI score
    category: 'pending' | 'Food' | 'Service' | 'Staff' | 'Ambience' | 'Cleanliness';
    tags?: string[];               // Optional keywords
    staffTagged?: string;          // Refers to a Staff document ID (Optional)
    status: 'normal' | 'critical' | 'escalated'; // If rating <= 2 or sentiment == negative -> 'critical'
    responseStatus: 'pending' | 'responded'; // Defaults to 'pending'
    externalTimestamp?: number;    // NEW: Google review time
    syncedAt?: Timestamp;          // NEW: Google sync time
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 4. Responses Collection
// Path: /responses/{responseId}
// ----------------------------------------------------------------------------
export interface Response {
    reviewId: string;              // Refers to a Review document ID
    responseText: string;
    autoGenerated: boolean;
    respondedBy: string;           // Refers to a User document ID
    respondedAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 5. Users Collection
// Path: /users/{userId} 
// Document ID MUST match Firebase Authentication UID
// ----------------------------------------------------------------------------
export interface User {
    name: string;
    email: string;                 // NEW
    role: 'admin' | 'branch_manager' | 'staff';
    branchId?: string;             // Refers to a Branch document ID (Null for admins)
}

// Helper to generate timestamps over the last few days
const getRecentTimestamp = (daysAgo: number) => {
    const date = new Date();
    date.setDate(date.getDate() - daysAgo);
    return Timestamp.fromDate(date);
};

export const mockReviews: Review[] = [
    // ------------------------------------------------------------------------
    // Branch 1: The Spice Symphony (branch_1) - 10 Reviews
    // ------------------------------------------------------------------------
    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_101',
        authorName: 'Rahul Sharma',
        rating: 5,
        reviewText: 'The food taste and quality were exceptional, with ingredients showing real freshness. Service speed was impressive. The overall cleanliness, especially the washroom hygiene, was top-notch. Loved the relaxing ambience and atmosphere. Great value for money, making it a perfect overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.92,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(1)
    },
    {
        branchId: 'branch_1',
        source: 'zomato',
        externalReviewId: 'z_102',
        authorName: 'Priya Desai',
        rating: 4,
        reviewText: 'Great food taste and reliable food quality. Freshness of the veggies was good. Service speed was slightly slow but acceptable. Cleanliness is maintained well, and washroom hygiene was adequate. The ambience and atmosphere are cozy. Good value for money. A solid overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.75,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_1',
        source: 'internal',
        authorName: 'Amit Patel',
        rating: 2,
        reviewText: 'Disappointed with the food taste; freshness and quality were lacking today. Service speed was incredibly slow. While the main area cleanliness was okay, washroom hygiene was poor. The ambience and atmosphere couldn’t save it. Poor value for money. Overall experience was frustrating.',
        sentiment: 'negative',
        sentimentScore: 0.15,
        category: 'Service',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_103',
        authorName: 'Neha Gupta',
        rating: 5,
        reviewText: 'Absolutely loved the food taste! High food quality and amazing freshness. Fast service speed. Flawless cleanliness and strict washroom hygiene. The ambience and atmosphere felt premium. Excellent value for money. Best overall experience in town.',
        sentiment: 'positive',
        sentimentScore: 0.95,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(3)
    },
    {
        branchId: 'branch_1',
        source: 'zomato',
        externalReviewId: 'z_104',
        authorName: 'Vikram Singh',
        rating: 3,
        reviewText: 'Food taste was decent, but food quality and freshness were inconsistent. Service speed was average. Cleanliness was fine, but washroom hygiene needs minor improvements. Good ambience and atmosphere. Okay value for money. Overall experience was just average.',
        sentiment: 'neutral',
        sentimentScore: 0.50,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(4)
    },
    {
        branchId: 'branch_1',
        source: 'internal',
        authorName: 'Anjali Verma',
        rating: 1,
        reviewText: 'Terrible food taste and zero freshness. Food quality was highly questionable. Service speed was atrocious. Cleanliness was bad, and washroom hygiene was unacceptable. Terrible ambience and atmosphere. Zero value for money. Ruined my overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.05,
        category: 'Cleanliness',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(5)
    },
    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_105',
        authorName: 'Karan Mehra',
        rating: 4,
        reviewText: 'Really enjoyed the food taste. Good food quality and noticeable freshness. Service speed was decent. Cleanliness is great, washroom hygiene is well-kept. The ambience and atmosphere are perfect for families. Fair value for money. Will repeat the overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.80,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(6)
    },
    {
        branchId: 'branch_1',
        source: 'zomato',
        externalReviewId: 'z_106',
        authorName: 'Rohan Joshi',
        rating: 5,
        reviewText: 'Superb food taste and unmatched food quality. The freshness of the seafood was great. Service speed was blazing fast. Perfect cleanliness and brilliant washroom hygiene. Vibrant ambience and atmosphere. High value for money. 10/10 overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.98,
        category: 'Service',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(7)
    },
    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_107',
        authorName: 'Sneha Reddy',
        rating: 3,
        reviewText: 'Average food taste. Food quality and freshness were okay, nothing special. Service speed was slow during rush hour. General cleanliness was good, but washroom hygiene was slipping. Lively ambience and atmosphere. Moderate value for money. An okay overall experience.',
        sentiment: 'neutral',
        sentimentScore: 0.45,
        category: 'Service',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(8)
    },
    {
        branchId: 'branch_1',
        source: 'internal',
        authorName: 'Deepak Chahar',
        rating: 4,
        reviewText: 'Brilliant food taste! The food quality and freshness stand out. Service speed was prompt. Great job on cleanliness and washroom hygiene. The ambience and atmosphere were very relaxing. Definitely good value for money. A lovely overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.85,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(9)
    },

    // ------------------------------------------------------------------------
    // Branch 2: Ocean Bites (branch_2) - 10 Reviews
    // ------------------------------------------------------------------------
    {
        branchId: 'branch_2',
        source: 'zomato',
        externalReviewId: 'z_201',
        authorName: 'Pooja Nair',
        rating: 5,
        reviewText: 'The seafood food taste is incredible. Top-tier food quality and freshness. Service speed was unmatched. Spotless cleanliness and great washroom hygiene. The seaside ambience and atmosphere are breathtaking. Excellent value for money. A stellar overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.96,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(1)
    },
    {
        branchId: 'branch_2',
        source: 'google',
        externalReviewId: 'g_202',
        authorName: 'Arjun Das',
        rating: 2,
        reviewText: 'Average food taste, but food quality and freshness were very poor today. Service speed was dragged out. Basic cleanliness, but washroom hygiene was severely lacking. Ambience and atmosphere were too noisy. Low value for money. Bad overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.20,
        category: 'Cleanliness',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_2',
        source: 'internal',
        authorName: 'Meera Rajput',
        rating: 4,
        reviewText: 'Loved the spicy food taste. Good food quality and great freshness. Service speed was fairly quick. Satisfactory cleanliness and clean washroom hygiene. Cozy ambience and atmosphere. Reasonable value for money. Highly recommend the overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.78,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(3)
    },
    {
        branchId: 'branch_2',
        source: 'google',
        externalReviewId: 'g_203',
        authorName: 'Ravi Kumar',
        rating: 3,
        reviewText: 'Food taste was okay, food quality and freshness were standard. Service speed was a bit delayed. Cleanliness was fine, washroom hygiene needs a check. Ambience and atmosphere were pleasant. Okay value for money. Decent overall experience.',
        sentiment: 'neutral',
        sentimentScore: 0.55,
        category: 'Service',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(4)
    },
    {
        branchId: 'branch_2',
        source: 'zomato',
        externalReviewId: 'z_204',
        authorName: 'Suresh Pillai',
        rating: 5,
        reviewText: 'Fantastic food taste! Food quality and ingredient freshness are premium. Amazing service speed. Complete cleanliness and top washroom hygiene. Beautiful ambience and atmosphere. Superb value for money. Flawless overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.99,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(5)
    },
    {
        branchId: 'branch_2',
        source: 'internal',
        authorName: 'Kavita Menon',
        rating: 1,
        reviewText: 'Horrible food taste, no freshness, poor food quality. Service speed was non-existent. Failed on cleanliness and washroom hygiene was gross. Dull ambience and atmosphere. Complete waste of value for money. A traumatic overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.02,
        category: 'Staff',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(6)
    },
    {
        branchId: 'branch_2',
        source: 'google',
        externalReviewId: 'g_205',
        authorName: 'Ajay Dev',
        rating: 4,
        reviewText: 'Great food taste and high food quality. Good freshness in the salads. Quick service speed. Good cleanliness and maintained washroom hygiene. Lovely ambience and atmosphere. Good value for money. A very satisfying overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.82,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(7)
    },
    {
        branchId: 'branch_2',
        source: 'zomato',
        externalReviewId: 'z_206',
        authorName: 'Nisha Kaur',
        rating: 2,
        reviewText: 'Food taste was bland. Poor food quality and lack of freshness. Service speed was frustrating. Cleanliness was sub-par; washroom hygiene was neglected. Noisy ambience and atmosphere. Bad value for money. Would not repeat this overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.25,
        category: 'Food',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(8)
    },
    {
        branchId: 'branch_2',
        source: 'google',
        externalReviewId: 'g_207',
        authorName: 'Tanya Sharma',
        rating: 5,
        reviewText: 'Yummy food taste! Exceptional food quality and freshness. Very fast service speed. Impressive cleanliness and excellent washroom hygiene. Great lighting, ambience and atmosphere. Great value for money. A memorable overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.94,
        category: 'Cleanliness',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(9)
    },
    {
        branchId: 'branch_2',
        source: 'internal',
        authorName: 'Varun Dhawan',
        rating: 3,
        reviewText: 'Standard food taste. Food quality and freshness were hit or miss. Service speed was fine. Cleanliness was okay, but washroom hygiene requires attention. Nice ambience and atmosphere. Average value for money. A middle-of-the-road overall experience.',
        sentiment: 'neutral',
        sentimentScore: 0.50,
        category: 'Service',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(10)
    },

    // ------------------------------------------------------------------------
    // Branch 3: Bella Italia (branch_3) - 10 Reviews
    // ------------------------------------------------------------------------
    {
        branchId: 'branch_3',
        source: 'google',
        externalReviewId: 'g_301',
        authorName: 'Gaurav Jain',
        rating: 5,
        reviewText: 'Authentic food taste! Brilliant food quality and pasta freshness. Service speed was perfect. Outstanding cleanliness and washroom hygiene. Romantic ambience and atmosphere. Total value for money. A beautiful overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.95,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(1)
    },
    {
        branchId: 'branch_3',
        source: 'zomato',
        externalReviewId: 'z_302',
        authorName: 'Simran Chawla',
        rating: 4,
        reviewText: 'Good food taste and reliable food quality with evident freshness. Service speed was quick enough. Cleanliness was fine and washroom hygiene was good. The Italian ambience and atmosphere are lovely. Great value for money. A happy overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.85,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_3',
        source: 'internal',
        authorName: 'Rishabh Pant',
        rating: 2,
        reviewText: 'Disappointing food taste. Food quality and freshness fell short. Service speed was very slow. Cleanliness was barely acceptable and washroom hygiene was poor. Ambience and atmosphere felt crowded. Not good value for money. A sad overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.18,
        category: 'Service',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(3)
    },
    {
        branchId: 'branch_3',
        source: 'google',
        externalReviewId: 'g_303',
        authorName: 'Kriti Sanon',
        rating: 5,
        reviewText: 'Incredible food taste! Top food quality and undeniable freshness. Prompt service speed. Great cleanliness and pristine washroom hygiene. Elegant ambience and atmosphere. Superb value for money. A luxury overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.97,
        category: 'Cleanliness',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(4)
    },
    {
        branchId: 'branch_3',
        source: 'zomato',
        externalReviewId: 'z_304',
        authorName: 'Aditya Roy',
        rating: 3,
        reviewText: 'Food taste was fine, food quality and freshness were average. Service speed was decent. Cleanliness was moderate, washroom hygiene needs work. Ambience and atmosphere were okay. Standard value for money. An acceptable overall experience.',
        sentiment: 'neutral',
        sentimentScore: 0.48,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(5)
    },
    {
        branchId: 'branch_3',
        source: 'internal',
        authorName: 'Priyanka Bose',
        rating: 1,
        reviewText: 'Awful food taste, zero food quality or freshness. Service speed was the worst. Cleanliness was completely ignored, washroom hygiene was disgusting. Ambience and atmosphere were chaotic. Zero value for money. A terrible overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.05,
        category: 'Cleanliness',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(6)
    },
    {
        branchId: 'branch_3',
        source: 'google',
        externalReviewId: 'g_305',
        authorName: 'Siddharth Malhotra',
        rating: 4,
        reviewText: 'Really liked the food taste and food quality. Good freshness all around. Service speed was attentive. Good cleanliness and washroom hygiene. Warm ambience and atmosphere. Good value for money. A delightful overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.81,
        category: 'Staff',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(7)
    },
    {
        branchId: 'branch_3',
        source: 'zomato',
        externalReviewId: 'z_306',
        authorName: 'Alia Bhatt',
        rating: 5,
        reviewText: 'Perfect food taste! The food quality and freshness are amazing. Very quick service speed. Exemplary cleanliness and top washroom hygiene. Beautiful ambience and atmosphere. Fantastic value for money. Best overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.99,
        category: 'Food',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(8)
    },
    {
        branchId: 'branch_3',
        source: 'google',
        externalReviewId: 'g_307',
        authorName: 'Tiger Shroff',
        rating: 2,
        reviewText: 'Not a fan of the food taste. Food quality and freshness were lacking. Service speed was too slow. Cleanliness was messy and washroom hygiene was ignored. Ambience and atmosphere were dull. Poor value for money. A bad overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.22,
        category: 'Service',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(9)
    },
    {
        branchId: 'branch_3',
        source: 'internal',
        authorName: 'Disha Patani',
        rating: 4,
        reviewText: 'Great food taste and high food quality with excellent freshness. Service speed was fast. Good cleanliness and proper washroom hygiene. Very aesthetic ambience and atmosphere. Worth the value for money. A fun overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.88,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(10)
    },

    // ------------------------------------------------------------------------
    // Branch 4: Tokyo Drift Sushi (branch_4) - 10 Reviews
    // ------------------------------------------------------------------------
    {
        branchId: 'branch_4',
        source: 'google',
        externalReviewId: 'g_401',
        authorName: 'Manoj Bajpayee',
        rating: 5,
        reviewText: 'Unreal food taste! The food quality and sushi freshness are unparalleled. Service speed was swift. Immaculate cleanliness and great washroom hygiene. The neon ambience and atmosphere are cool. Total value for money. A stellar overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.96,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(1)
    },
    {
        branchId: 'branch_4',
        source: 'zomato',
        externalReviewId: 'z_402',
        authorName: 'Pankaj Tripathi',
        rating: 4,
        reviewText: 'Very good food taste. Food quality and freshness were top notch. Service speed was fairly quick. Nice cleanliness and good washroom hygiene. Calm ambience and atmosphere. Fair value for money. A great overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.84,
        category: 'Staff',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_4',
        source: 'internal',
        authorName: 'Nawazuddin Siddiqui',
        rating: 3,
        reviewText: 'Food taste was okay. Food quality and freshness were hit-and-miss. Service speed was slow today. Cleanliness was average, washroom hygiene needs a deep clean. Standard ambience and atmosphere. Moderate value for money. Just an okay overall experience.',
        sentiment: 'neutral',
        sentimentScore: 0.52,
        category: 'Cleanliness',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(3)
    },
    {
        branchId: 'branch_4',
        source: 'google',
        externalReviewId: 'g_403',
        authorName: 'Radhika Apte',
        rating: 1,
        reviewText: 'Worst food taste ever. Zero food quality and no freshness. Service speed was terrible. Failed in cleanliness and the washroom hygiene was appalling. Gloomy ambience and atmosphere. No value for money. A disastrous overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.05,
        category: 'Food',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(4)
    },
    {
        branchId: 'branch_4',
        source: 'zomato',
        externalReviewId: 'z_404',
        authorName: 'Vicky Kaushal',
        rating: 5,
        reviewText: 'Amazing food taste! The food quality and fish freshness were out of this world. Superb service speed. Excellent cleanliness and washroom hygiene. Great Japanese ambience and atmosphere. Perfect value for money. A flawless overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.98,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(5)
    },
    {
        branchId: 'branch_4',
        source: 'internal',
        authorName: 'Ayushmann Khurrana',
        rating: 4,
        reviewText: 'Delicious food taste and consistent food quality. Great freshness. Service speed was efficient. Very good cleanliness and washroom hygiene. Relaxing ambience and atmosphere. Good value for money. A highly satisfying overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.87,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(6)
    },
    {
        branchId: 'branch_4',
        source: 'google',
        externalReviewId: 'g_405',
        authorName: 'Rajkummar Rao',
        rating: 2,
        reviewText: 'Food taste was underwhelming. Poor food quality and lack of freshness. Service speed was highly delayed. Cleanliness was questionable; washroom hygiene was bad. Loud ambience and atmosphere. Poor value for money. A disappointing overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.19,
        category: 'Service',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(7)
    },
    {
        branchId: 'branch_4',
        source: 'zomato',
        externalReviewId: 'z_406',
        authorName: 'Bhumi Pednekar',
        rating: 5,
        reviewText: 'Incredible food taste and food quality! Maximum freshness. Blazing service speed. Spotless cleanliness and superior washroom hygiene. The modern ambience and atmosphere are perfect. High value for money. A top-tier overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.99,
        category: 'Service',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(8)
    },
    {
        branchId: 'branch_4',
        source: 'google',
        externalReviewId: 'g_407',
        authorName: 'Taapsee Pannu',
        rating: 3,
        reviewText: 'Average food taste. Food quality and freshness were acceptable. Service speed could be better. Cleanliness was fine, but washroom hygiene needs attention. Decent ambience and atmosphere. Fair value for money. A standard overall experience.',
        sentiment: 'neutral',
        sentimentScore: 0.49,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(9)
    },
    {
        branchId: 'branch_4',
        source: 'internal',
        authorName: 'Kartik Aaryan',
        rating: 4,
        reviewText: 'Very nice food taste. Excellent food quality and freshness. Service speed was prompt. Good cleanliness and neat washroom hygiene. Great aesthetic ambience and atmosphere. Well worth the value for money. A solid overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.82,
        category: 'Cleanliness',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(10)
    },

    // ------------------------------------------------------------------------
    // Branch 5: The Daily Roast (branch_5) - 10 Reviews
    // ------------------------------------------------------------------------
    {
        branchId: 'branch_5',
        source: 'google',
        externalReviewId: 'g_501',
        authorName: 'Sara Ali Khan',
        rating: 5,
        reviewText: 'Perfect coffee and food taste! Great food quality and freshness in the pastries. Super fast service speed. Excellent cleanliness and washroom hygiene. Cozy cafe ambience and atmosphere. High value for money. A wonderful overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.96,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(1)
    },
    {
        branchId: 'branch_5',
        source: 'zomato',
        externalReviewId: 'z_502',
        authorName: 'Janhvi Kapoor',
        rating: 4,
        reviewText: 'Good food taste and food quality. Appreciated the freshness of the sandwiches. Service speed was quick. Nice cleanliness and acceptable washroom hygiene. Peaceful ambience and atmosphere. Good value for money. A pleasant overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.80,
        category: 'Food',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_5',
        source: 'internal',
        authorName: 'Ishaan Khatter',
        rating: 2,
        reviewText: 'Food taste was bitter today. Food quality and freshness were poor. Service speed was terribly slow. Cleanliness was messy on the tables, washroom hygiene was bad. Crowded ambience and atmosphere. Low value for money. A bad overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.20,
        category: 'Cleanliness',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(3)
    },
    {
        branchId: 'branch_5',
        source: 'google',
        externalReviewId: 'g_503',
        authorName: 'Ananya Panday',
        rating: 5,
        reviewText: 'Amazing food taste! Outstanding food quality and freshness. Service speed was excellent. Perfect cleanliness and great washroom hygiene. Love the quiet ambience and atmosphere. Super value for money. A lovely overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.94,
        category: 'Staff',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(4)
    },
    {
        branchId: 'branch_5',
        source: 'zomato',
        externalReviewId: 'z_504',
        authorName: 'Tara Sutaria',
        rating: 3,
        reviewText: 'Okay food taste. Food quality and freshness were standard. Service speed was average. Cleanliness was okay, but washroom hygiene was neglected. Ambience and atmosphere were a bit loud. Average value for money. A mediocre overall experience.',
        sentiment: 'neutral',
        sentimentScore: 0.50,
        category: 'Service',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(5)
    },
    {
        branchId: 'branch_5',
        source: 'internal',
        authorName: 'Vijay Varma',
        rating: 1,
        reviewText: 'Terrible food taste. Bad food quality and stale freshness. Service speed was awful. Cleanliness was non-existent, washroom hygiene was repulsive. Uncomfortable ambience and atmosphere. Zero value for money. A ruined overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.08,
        category: 'Cleanliness',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(6)
    },
    {
        branchId: 'branch_5',
        source: 'google',
        externalReviewId: 'g_505',
        authorName: 'Gully Boy',
        rating: 4,
        reviewText: 'Really good food taste and food quality. Great freshness overall. Service speed was efficient. Good cleanliness and decent washroom hygiene. Great chilling ambience and atmosphere. Solid value for money. A great overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.85,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(7)
    },
    {
        branchId: 'branch_5',
        source: 'zomato',
        externalReviewId: 'z_506',
        authorName: 'Mrunal Thakur',
        rating: 5,
        reviewText: 'Fantastic food taste! Top food quality and ultimate freshness. Rapid service speed. Spotless cleanliness and superior washroom hygiene. Best coffee-shop ambience and atmosphere. Excellent value for money. A perfect overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.98,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(8)
    },
    {
        branchId: 'branch_5',
        source: 'google',
        externalReviewId: 'g_507',
        authorName: 'Sobhita Dhulipala',
        rating: 2,
        reviewText: 'Below average food taste. Poor food quality and missing freshness. Service speed was frustratingly slow. Cleanliness was subpar; washroom hygiene was poor. Ambience and atmosphere felt stuffy. Not good value for money. A bad overall experience.',
        sentiment: 'negative',
        sentimentScore: 0.25,
        category: 'Service',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(9)
    },
    {
        branchId: 'branch_5',
        source: 'internal',
        authorName: 'Ali Fazal',
        rating: 4,
        reviewText: 'Great food taste! Impressive food quality and freshness. Service speed was quite fast. Cleanliness was well maintained, including washroom hygiene. Relaxing ambience and atmosphere. Very good value for money. A highly positive overall experience.',
        sentiment: 'positive',
        sentimentScore: 0.89,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(10)
    }
];
