import { Timestamp } from 'firebase/firestore';

// ----------------------------------------------------------------------------
// 1. Branches Collection
// Path: /branches/{branchId}
// ----------------------------------------------------------------------------
export interface Branch {
    name: string;
    location: string;
    managerId: string;
    placeId: string;               // NEW: Google Places ID
    status: 'active' | 'inactive';
    totalReviews: number;          // Default: 0
    averageRating: number;         // Default: 0
    positiveReviews: number;       // Default: 0
    negativeReviews: number;       // Default: 0
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 2. Staff Collection
// Path: /staff/{staffId}
// ----------------------------------------------------------------------------
export interface Staff {
    name: string;
    branchId: string;              // Refers to a Branch document ID
    role: string;                  // e.g., 'Manager', 'Waiter', 'Chef'
    email?: string;                // Optional
    performanceScore: number;      // Default: 0
    totalReviewsTagged: number;    // Default: 0
    averageRating: number;         // Default: 0
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 3. Reviews Collection
// Path: /reviews/{reviewId}
// ----------------------------------------------------------------------------
export interface Review {
    branchId: string;              // Refers to a Branch document ID
    source: 'internal' | 'google' | 'zomato';
    externalReviewId?: string;     // NEW: Unique ID for duplicate prevention
    authorName: string;            // NEW: Review author
    rating: number;                // 1-5 scale
    reviewText: string;
    sentiment: 'pending' | 'positive' | 'neutral' | 'negative';
    sentimentScore: number;        // 0-1 AI score
    category: 'pending' | 'Food' | 'Service' | 'Staff' | 'Ambience' | 'Cleanliness';
    tags?: string[];               // Optional keywords
    staffTagged?: string;          // Refers to a Staff document ID (Optional)
    status: 'normal' | 'critical' | 'escalated'; // If rating <= 2 or sentiment == negative -> 'critical'
    responseStatus: 'pending' | 'responded'; // Defaults to 'pending'
    externalTimestamp?: number;    // NEW: Google review time
    syncedAt?: Timestamp;          // NEW: Google sync time
    createdAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 4. Responses Collection
// Path: /responses/{responseId}
// ----------------------------------------------------------------------------
export interface Response {
    reviewId: string;              // Refers to a Review document ID
    responseText: string;
    autoGenerated: boolean;
    respondedBy: string;           // Refers to a User document ID
    respondedAt: Timestamp;
}

// ----------------------------------------------------------------------------
// 5. Users Collection
// Path: /users/{userId} 
// Document ID MUST match Firebase Authentication UID
// ----------------------------------------------------------------------------
export interface User {
    name: string;
    email: string;                 // NEW
    role: 'admin' | 'branch_manager' | 'staff';
    branchId?: string;             // Refers to a Branch document ID (Null for admins)
}

// Helper to generate timestamps over the last few days
const getRecentTimestamp = (daysAgo: number) => {
    const date = new Date();
    date.setDate(date.getDate() - daysAgo);
    return Timestamp.fromDate(date);
};

export const mockReviews: Review[] = [

    // ------------------------------------------------------------------------
    // Branch 1: Pizza Hut Mumbai (branch_1)
    // ------------------------------------------------------------------------

    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_101',
        authorName: 'Rahul Sharma',
        rating: 5,
        reviewText: 'Had a wonderful experience at the Pizza Hut Mumbai outlet. The pizza was served piping hot with a perfectly baked crust and generous toppings. The cheese quality was excellent and the flavors were well balanced. Service was quick even during dinner rush, and the staff remained courteous throughout. The outlet was clean, well-lit, and comfortable for family dining. Definitely one of the better experiences I have had at this branch.',
        sentiment: 'positive',
        sentimentScore: 0.94,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(1)
    },
    {
        branchId: 'branch_1',
        source: 'zomato',
        externalReviewId: 'z_102',
        authorName: 'Priya Desai',
        rating: 4,
        reviewText: 'The overall dining experience was quite satisfying. The cheese burst pizza tasted fresh and flavorful, and the garlic bread was crispy and well seasoned. Service was slightly slow due to weekend crowd, but the staff handled everything professionally. Cleanliness standards were maintained properly. Would definitely visit again.',
        sentiment: 'positive',
        sentimentScore: 0.82,
        category: 'Service',
        status: 'normal',
        responseStatus: 'responded',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_1',
        source: 'internal',
        authorName: 'Amit Patel',
        rating: 2,
        reviewText: 'The pizza tasted average and the crust felt slightly undercooked. Service took longer than expected, and we had to follow up twice for our order. The dining area was reasonably clean, but the overall experience did not match expectations. Hoping for better consistency next time.',
        sentiment: 'negative',
        sentimentScore: 0.22,
        category: 'Service',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(2)
    },
    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_103',
        authorName: 'Neha Gupta',
        rating: 5,
        reviewText: 'Absolutely loved the ambience and food quality here. The farmhouse pizza was loaded with fresh vegetables and the cheese pull was perfect. Service was prompt and attentive. The outlet maintains high hygiene standards. A great place for weekend dinners with family.',
        sentiment: 'positive',
        sentimentScore: 0.96,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(3)
    },

    // Remaining 6 of branch_1 shortened here for space balance but still long, realistic

    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_104',
        authorName: 'Karan Mehra',
        rating: 4,
        reviewText: 'Very good quality pizza with fresh toppings and balanced seasoning. Service was polite and efficient. The outlet was clean and well managed.',
        sentiment: 'positive',
        sentimentScore: 0.85,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(4)
    },
    {
        branchId: 'branch_1',
        source: 'zomato',
        externalReviewId: 'z_105',
        authorName: 'Sneha Reddy',
        rating: 3,
        reviewText: 'Food was decent but waiting time during peak hours was slightly high. Staff was polite though. Average experience overall.',
        sentiment: 'neutral',
        sentimentScore: 0.50,
        category: 'Service',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(5)
    },
    {
        branchId: 'branch_1',
        source: 'internal',
        authorName: 'Deepak Chahar',
        rating: 4,
        reviewText: 'Enjoyed the stuffed crust pizza and brownie dessert. Service was attentive and seating was comfortable.',
        sentiment: 'positive',
        sentimentScore: 0.87,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(6)
    },
    {
        branchId: 'branch_1',
        source: 'google',
        externalReviewId: 'g_106',
        authorName: 'Riya Kapoor',
        rating: 5,
        reviewText: 'Excellent food quality and quick service. Clean outlet and great ambience for casual dining.',
        sentiment: 'positive',
        sentimentScore: 0.95,
        category: 'Ambience',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(7)
    },
    {
        branchId: 'branch_1',
        source: 'zomato',
        externalReviewId: 'z_107',
        authorName: 'Vikas Nair',
        rating: 2,
        reviewText: 'Pizza was lukewarm and service response was slow. Not the best visit this time.',
        sentiment: 'negative',
        sentimentScore: 0.20,
        category: 'Food',
        status: 'critical',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(8)
    },
    {
        branchId: 'branch_1',
        source: 'internal',
        authorName: 'Ananya Joshi',
        rating: 3,
        reviewText: 'Decent pizza taste but nothing exceptional. Service could improve during rush hours.',
        sentiment: 'neutral',
        sentimentScore: 0.52,
        category: 'Service',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(9)
    },

    // ------------------------------------------------------------------------
    // Branch 2: Pizza Hut Navi Mumbai (branch_2)
    // ------------------------------------------------------------------------

    {
        branchId: 'branch_2',
        source: 'google',
        externalReviewId: 'g_201',
        authorName: 'Saurabh Kulkarni',
        rating: 5,
        reviewText: 'Fantastic experience at the Navi Mumbai outlet. The pizza was served hot with a crispy crust and generous toppings. Staff was friendly and attentive. Clean and well-maintained environment.',
        sentiment: 'positive',
        sentimentScore: 0.95,
        category: 'Food',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(1)
    },

    // I will now complete remaining branches concisely but correctly formatted to fit message limit

    // Branch 2 remaining 9
    {
        branchId: 'branch_2',
        source: 'zomato',
        externalReviewId: 'z_202',
        authorName: 'Meera Shah',
        rating: 4,
        reviewText: 'Good taste and quick takeaway service. Packaging was neat and food was fresh.',
        sentiment: 'positive',
        sentimentScore: 0.82,
        category: 'Service',
        status: 'normal',
        responseStatus: 'pending',
        createdAt: getRecentTimestamp(2)
    },

    // Due to message length limit, continuing in next reply...
// ------------------------------------------------------------------------
// Branch 2: Pizza Hut Navi Mumbai (branch_2) - Remaining 8 Reviews
// ------------------------------------------------------------------------

{
    branchId: 'branch_2',
        source: 'google',
            externalReviewId: 'g_203',
                authorName: 'Arjun Malhotra',
                    rating: 2,
                        reviewText: 'The pizza toppings were uneven and the crust felt slightly chewy. Service took longer than expected and the staff seemed a bit overwhelmed during peak hours. Cleanliness was average but could definitely improve. Overall not the best experience at this branch.',
                            sentiment: 'negative',
                                sentimentScore: 0.25,
                                    category: 'Food',
                                        status: 'critical',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(3)
},
{
    branchId: 'branch_2',
        source: 'zomato',
            externalReviewId: 'z_204',
                authorName: 'Tanvi Shah',
                    rating: 5,
                        reviewText: 'Amazing experience at the Navi Mumbai outlet. The cheese burst pizza was perfectly baked and loaded with toppings. Staff was friendly and attentive. The outlet was clean and well organized. Highly recommend this branch.',
                            sentiment: 'positive',
                                sentimentScore: 0.96,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(4)
},
{
    branchId: 'branch_2',
        source: 'internal',
            authorName: 'Harsh Vora',
                rating: 3,
                    reviewText: 'Food tasted fine but waiting time was slightly longer than usual. Staff remained polite and the dining area was fairly clean. An average but acceptable experience.',
                        sentiment: 'neutral',
                            sentimentScore: 0.52,
                                category: 'Service',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(5)
},
{
    branchId: 'branch_2',
        source: 'google',
            externalReviewId: 'g_205',
                authorName: 'Simran Kaur',
                    rating: 4,
                        reviewText: 'Loved the combo deals and overall quality of food. Pizza was served hot and fresh. Service was efficient and ambience was comfortable for family dining.',
                            sentiment: 'positive',
                                sentimentScore: 0.88,
                                    category: 'Ambience',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(6)
},
{
    branchId: 'branch_2',
        source: 'zomato',
            externalReviewId: 'z_206',
                authorName: 'Aditya Rao',
                    rating: 1,
                        reviewText: 'Very disappointing visit. The order was incorrect and replacement took a long time. The pizza lacked flavor and staff response was slow. Not satisfied with the overall experience.',
                            sentiment: 'negative',
                                sentimentScore: 0.10,
                                    category: 'Service',
                                        status: 'critical',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(7)
},
{
    branchId: 'branch_2',
        source: 'internal',
            authorName: 'Neha Bhatia',
                rating: 5,
                    reviewText: 'Fantastic service and great tasting pizza. Ingredients were fresh and crust was perfectly baked. The outlet maintains excellent hygiene standards.',
                        sentiment: 'positive',
                            sentimentScore: 0.97,
                                category: 'Cleanliness',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(8)
},
{
    branchId: 'branch_2',
        source: 'google',
            externalReviewId: 'g_207',
                authorName: 'Rajat Kapoor',
                    rating: 3,
                        reviewText: 'Decent quality food but service can improve during rush hours. Ambience is pleasant and seating is comfortable.',
                            sentiment: 'neutral',
                                sentimentScore: 0.50,
                                    category: 'Service',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(9)
},
{
    branchId: 'branch_2',
        source: 'zomato',
            externalReviewId: 'z_208',
                authorName: 'Bhavna Iyer',
                    rating: 4,
                        reviewText: 'Good food quality and timely service. Pizza tasted fresh and portion sizes were adequate. Would recommend for family outings.',
                            sentiment: 'positive',
                                sentimentScore: 0.86,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(10)
},

// ------------------------------------------------------------------------
// Branch 3: Pizza Hut Thane (branch_3) - 10 Reviews
// ------------------------------------------------------------------------

{
    branchId: 'branch_3',
        source: 'google',
            externalReviewId: 'g_301',
                authorName: 'Manish Gupta',
                    rating: 5,
                        reviewText: 'Excellent experience at the Thane outlet. The cheese was fresh and toppings were generous. Staff was welcoming and service was quick. The dining area was neat and clean.',
                            sentiment: 'positive',
                                sentimentScore: 0.95,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(1)
},

{
    branchId: 'branch_3',
        source: 'zomato',
            externalReviewId: 'z_302',
                authorName: 'Aisha Khan',
                    rating: 4,
                        reviewText: 'Loved the ambience and comfortable seating. Pizza tasted great and was served hot. Service was attentive.',
                            sentiment: 'positive',
                                sentimentScore: 0.84,
                                    category: 'Ambience',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(2)
},

{
    branchId: 'branch_3',
        source: 'internal',
            authorName: 'Ritesh Jain',
                rating: 2,
                    reviewText: 'Pizza was lukewarm and service took too long. Staff was polite but the delay affected the overall experience.',
                        sentiment: 'negative',
                            sentimentScore: 0.22,
                                category: 'Service',
                                    status: 'critical',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(3)
},

{
    branchId: 'branch_3',
        source: 'google',
            externalReviewId: 'g_303',
                authorName: 'Shreya Patil',
                    rating: 5,
                        reviewText: 'Amazing dessert options and quick service. The stuffed crust pizza was delicious and perfectly baked.',
                            sentiment: 'positive',
                                sentimentScore: 0.97,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(4)
},

{
    branchId: 'branch_3',
        source: 'zomato',
            externalReviewId: 'z_304',
                authorName: 'Akash Thakur',
                    rating: 3,
                        reviewText: 'Decent food quality but lacked seasoning. Service was average.',
                            sentiment: 'neutral',
                                sentimentScore: 0.50,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(5)
},

{
    branchId: 'branch_3',
        source: 'internal',
            authorName: 'Nandini Shetty',
                rating: 4,
                    reviewText: 'Clean outlet and well organized staff. Pizza was served fresh and hot.',
                        sentiment: 'positive',
                            sentimentScore: 0.88,
                                category: 'Cleanliness',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(6)
},

{
    branchId: 'branch_3',
        source: 'google',
            externalReviewId: 'g_305',
                authorName: 'Divya Arora',
                    rating: 1,
                        reviewText: 'Very poor experience. Pizza tasted stale and tables were not cleaned properly.',
                            sentiment: 'negative',
                                sentimentScore: 0.09,
                                    category: 'Cleanliness',
                                        status: 'critical',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(7)
},

{
    branchId: 'branch_3',
        source: 'zomato',
            externalReviewId: 'z_306',
                authorName: 'Siddharth Roy',
                    rating: 5,
                        reviewText: 'Perfect place for weekend dinners. Food was fresh and service was excellent.',
                            sentiment: 'positive',
                                sentimentScore: 0.96,
                                    category: 'Service',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(8)
},

{
    branchId: 'branch_3',
        source: 'google',
            externalReviewId: 'g_307',
                authorName: 'Kavya Menon',
                    rating: 3,
                        reviewText: 'Food was okay but service can improve during busy hours.',
                            sentiment: 'neutral',
                                sentimentScore: 0.51,
                                    category: 'Service',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(9)
},

{
    branchId: 'branch_3',
        source: 'internal',
            authorName: 'Varun Sethi',
                rating: 4,
                    reviewText: 'Good quality ingredients and smooth billing process. Overall pleasant experience.',
                        sentiment: 'positive',
                            sentimentScore: 0.87,
                                category: 'Staff',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(10)
},

// ------------------------------------------------------------------------
// Branch 4 & 5 continuation follows same pattern...

// ------------------------------------------------------------------------
// Branch 4: Pizza Hut Andheri (branch_4) - 10 Reviews
// ------------------------------------------------------------------------

{
    branchId: 'branch_4',
        source: 'google',
            externalReviewId: 'g_401',
                authorName: 'Mitali Das',
                    rating: 5,
                        reviewText: 'Outstanding experience at the Andheri outlet. The pizza crust was perfectly baked and toppings were fresh and flavorful. Service was quick and staff was attentive. The outlet was clean and had a pleasant ambience suitable for family dining.',
                            sentiment: 'positive',
                                sentimentScore: 0.95,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(1)
},
{
    branchId: 'branch_4',
        source: 'zomato',
            externalReviewId: 'z_402',
                authorName: 'Ankit Tiwari',
                    rating: 4,
                        reviewText: 'Garlic bread was crispy and delicious. Pizza was served hot and tasted great. Service was smooth and billing was fast. Overall a satisfying visit.',
                            sentiment: 'positive',
                                sentimentScore: 0.86,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(2)
},
{
    branchId: 'branch_4',
        source: 'internal',
            authorName: 'Shruti Kulkarni',
                rating: 2,
                    reviewText: 'Pizza crust felt dry and service response time was slow. Staff was polite but overall experience was below expectations.',
                        sentiment: 'negative',
                            sentimentScore: 0.24,
                                category: 'Service',
                                    status: 'critical',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(3)
},
{
    branchId: 'branch_4',
        source: 'google',
            externalReviewId: 'g_403',
                authorName: 'Yash Malhotra',
                    rating: 5,
                        reviewText: 'Excellent ambience and quick service. The cheese burst pizza was fresh and flavorful. Clean dining area and well-maintained washrooms.',
                            sentiment: 'positive',
                                sentimentScore: 0.96,
                                    category: 'Ambience',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(4)
},
{
    branchId: 'branch_4',
        source: 'zomato',
            externalReviewId: 'z_404',
                authorName: 'Payal Mehra',
                    rating: 3,
                        reviewText: 'Food was decent but service was slightly delayed due to crowd. Seating was comfortable and ambience was nice.',
                            sentiment: 'neutral',
                                sentimentScore: 0.52,
                                    category: 'Service',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(5)
},
{
    branchId: 'branch_4',
        source: 'internal',
            authorName: 'Gaurav Sharma',
                rating: 4,
                    reviewText: 'Fresh toppings and generous portion sizes. Service staff was friendly and attentive. Good experience overall.',
                        sentiment: 'positive',
                            sentimentScore: 0.88,
                                category: 'Food',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(6)
},
{
    branchId: 'branch_4',
        source: 'google',
            externalReviewId: 'g_405',
                authorName: 'Ruchi Jain',
                    rating: 1,
                        reviewText: 'Very frustrating visit. Order was delayed by almost 30 minutes and pizza was lukewarm when served. Not satisfied with service quality.',
                            sentiment: 'negative',
                                sentimentScore: 0.09,
                                    category: 'Service',
                                        status: 'critical',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(7)
},
{
    branchId: 'branch_4',
        source: 'zomato',
            externalReviewId: 'z_406',
                authorName: 'Krishna Iyer',
                    rating: 5,
                        reviewText: 'Loved the stuffed crust option. Perfect cheese pull and quick service. The outlet was clean and well managed.',
                            sentiment: 'positive',
                                sentimentScore: 0.97,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(8)
},
{
    branchId: 'branch_4',
        source: 'google',
            externalReviewId: 'g_407',
                authorName: 'Lavanya Pillai',
                    rating: 3,
                        reviewText: 'Food quality was acceptable but service could improve during busy hours. Overall average experience.',
                            sentiment: 'neutral',
                                sentimentScore: 0.50,
                                    category: 'Service',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(9)
},
{
    branchId: 'branch_4',
        source: 'internal',
            authorName: 'Mohit Arora',
                rating: 4,
                    reviewText: 'Nice family vibe and good quality pizza. Staff was helpful and billing process was smooth.',
                        sentiment: 'positive',
                            sentimentScore: 0.85,
                                category: 'Staff',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(10)
},

// ------------------------------------------------------------------------
// Branch 5: Pizza Hut Borivali (branch_5) - 10 Reviews
// ------------------------------------------------------------------------

{
    branchId: 'branch_5',
        source: 'google',
            externalReviewId: 'g_501',
                authorName: 'Abhishek Nair',
                    rating: 5,
                        reviewText: 'Great taste and perfect portion size. Pizza was served fresh and hot. Service was quick and the outlet was very clean.',
                            sentiment: 'positive',
                                sentimentScore: 0.95,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(1)
},
{
    branchId: 'branch_5',
        source: 'zomato',
            externalReviewId: 'z_502',
                authorName: 'Komal Shah',
                    rating: 4,
                        reviewText: 'Loved the cheese burst option and overall flavor. Staff was courteous and seating was comfortable.',
                            sentiment: 'positive',
                                sentimentScore: 0.84,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(2)
},
{
    branchId: 'branch_5',
        source: 'internal',
            authorName: 'Parth Desai',
                rating: 2,
                    reviewText: 'Pizza was slightly overcooked and crust felt dry. Service was slower than expected.',
                        sentiment: 'negative',
                            sentimentScore: 0.23,
                                category: 'Food',
                                    status: 'critical',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(3)
},
{
    branchId: 'branch_5',
        source: 'google',
            externalReviewId: 'g_503',
                authorName: 'Sana Mirza',
                    rating: 5,
                        reviewText: 'Very clean and well-managed outlet. Pizza tasted fresh and service was attentive.',
                            sentiment: 'positive',
                                sentimentScore: 0.96,
                                    category: 'Cleanliness',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(4)
},
{
    branchId: 'branch_5',
        source: 'zomato',
            externalReviewId: 'z_504',
                authorName: 'Tejaswini Kulkarni',
                    rating: 3,
                        reviewText: 'Okay experience overall. Food was decent but nothing extraordinary.',
                            sentiment: 'neutral',
                                sentimentScore: 0.50,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(5)
},
{
    branchId: 'branch_5',
        source: 'internal',
            authorName: 'Rohit Bansal',
                rating: 4,
                    reviewText: 'Quick takeaway service and good packaging. Pizza tasted fresh and toppings were generous.',
                        sentiment: 'positive',
                            sentimentScore: 0.88,
                                category: 'Service',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(6)
},
{
    branchId: 'branch_5',
        source: 'google',
            externalReviewId: 'g_505',
                authorName: 'Ananya Joshi',
                    rating: 1,
                        reviewText: 'Very disappointed. Food quality was poor and service response was slow. Not satisfied with this visit.',
                            sentiment: 'negative',
                                sentimentScore: 0.08,
                                    category: 'Service',
                                        status: 'critical',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(7)
},
{
    branchId: 'branch_5',
        source: 'zomato',
            externalReviewId: 'z_506',
                authorName: 'Krishna Menon',
                    rating: 5,
                        reviewText: 'Amazing flavors and quick service. The stuffed crust option was delicious and perfectly baked.',
                            sentiment: 'positive',
                                sentimentScore: 0.97,
                                    category: 'Food',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(8)
},
{
    branchId: 'branch_5',
        source: 'google',
            externalReviewId: 'g_507',
                authorName: 'Lavanya Rao',
                    rating: 3,
                        reviewText: 'Decent food but staff coordination can improve. Overall an average dining experience.',
                            sentiment: 'neutral',
                                sentimentScore: 0.51,
                                    category: 'Staff',
                                        status: 'normal',
                                            responseStatus: 'pending',
                                                createdAt: getRecentTimestamp(9)
},
{
    branchId: 'branch_5',
        source: 'internal',
            authorName: 'Vishal Yadav',
                rating: 4,
                    reviewText: 'Good ambience and tasty pizzas. Staff was polite and service was reasonably quick.',
                        sentiment: 'positive',
                            sentimentScore: 0.86,
                                category: 'Ambience',
                                    status: 'normal',
                                        responseStatus: 'pending',
                                            createdAt: getRecentTimestamp(10)
}
];